-- Foundation for extensible Aurore editorial structure and subject profiles.
-- This migration intentionally creates the schema only.
-- Editorial rules and subject-specific rules will be defined with the user in later steps.

create table public.aurora_editorial_structure_memory (
  id bigint generated by default as identity primary key,
  rule_key text not null,
  version integer not null default 1,
  title text not null,
  priority integer not null default 100,
  mandatory boolean not null default true,
  active boolean not null default false,
  content jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(rule_key, version)
);

create index aurora_editorial_structure_memory_active_idx
  on public.aurora_editorial_structure_memory (active, priority);

alter table public.aurora_editorial_structure_memory enable row level security;
revoke all on public.aurora_editorial_structure_memory from anon, authenticated;
grant all on public.aurora_editorial_structure_memory to service_role;

create table public.aurora_editorial_subject_profiles (
  id bigint generated by default as identity primary key,
  subject_key text not null unique,
  subject_name text not null,
  family_key text not null,
  parent_subject_key text null references public.aurora_editorial_subject_profiles(subject_key) on update cascade on delete set null,
  version integer not null default 1,
  status text not null default 'draft' check (status in ('draft','partial','ready','retired')),
  active boolean not null default false,
  content jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index aurora_editorial_subject_profiles_family_idx
  on public.aurora_editorial_subject_profiles (family_key, active);

alter table public.aurora_editorial_subject_profiles enable row level security;
revoke all on public.aurora_editorial_subject_profiles from anon, authenticated;
grant all on public.aurora_editorial_subject_profiles to service_role;

create table public.aurora_editorial_subject_aliases (
  id bigint generated by default as identity primary key,
  alias text not null unique,
  subject_key text not null references public.aurora_editorial_subject_profiles(subject_key) on update cascade on delete cascade,
  active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index aurora_editorial_subject_aliases_subject_idx
  on public.aurora_editorial_subject_aliases (subject_key, active);

alter table public.aurora_editorial_subject_aliases enable row level security;
revoke all on public.aurora_editorial_subject_aliases from anon, authenticated;
grant all on public.aurora_editorial_subject_aliases to service_role;
