create table if not exists public.aurora_editorial_memory (
  id bigint generated by default as identity primary key,
  rule_key text not null,
  version integer not null default 1 check (version > 0),
  title text not null,
  priority integer not null default 100,
  mandatory boolean not null default true,
  active boolean not null default true,
  content jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (rule_key, version)
);

create unique index if not exists aurora_editorial_memory_active_key_uq
  on public.aurora_editorial_memory (rule_key) where active;

create table if not exists public.aurora_math_editorial_memory (
  id bigint generated by default as identity primary key,
  rule_key text not null,
  version integer not null default 1 check (version > 0),
  title text not null,
  priority integer not null default 100,
  mandatory boolean not null default true,
  active boolean not null default true,
  content jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (rule_key, version)
);

create unique index if not exists aurora_math_editorial_memory_active_key_uq
  on public.aurora_math_editorial_memory (rule_key) where active;

create table if not exists public.aurora_editorial_memory_sessions (
  session_id uuid primary key default gen_random_uuid(),
  token_hash text not null unique,
  requested_subject text,
  requested_document_type text,
  requires_math boolean not null default false,
  general_rule_ids bigint[] not null default '{}'::bigint[],
  math_rule_ids bigint[] not null default '{}'::bigint[],
  general_memory_version integer,
  math_memory_version integer,
  bundle_sha256 text,
  consumer text not null default 'aurore-assistant',
  retrieved_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '30 minutes'),
  used_at timestamptz,
  used_ingest_id text,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists aurora_editorial_memory_sessions_active_idx
  on public.aurora_editorial_memory_sessions (expires_at, used_at);

alter table public.aurora_editorial_memory enable row level security;
alter table public.aurora_math_editorial_memory enable row level security;
alter table public.aurora_editorial_memory_sessions enable row level security;

revoke all on public.aurora_editorial_memory from public, anon, authenticated;
revoke all on public.aurora_math_editorial_memory from public, anon, authenticated;
revoke all on public.aurora_editorial_memory_sessions from public, anon, authenticated;
grant select on public.aurora_editorial_memory to service_role;
grant select on public.aurora_math_editorial_memory to service_role;
grant select, insert, update on public.aurora_editorial_memory_sessions to service_role;

insert into public.aurora_editorial_memory (rule_key,version,title,priority,content) values
('pipeline_and_gate',1,'Chaîne Aurore et barrière mémoire',1000,
 '{"purpose":"Récupérer les règles Aurore avant chaque injection éditoriale.","required_actions":["récupérer la mémoire générale","récupérer la mémoire spécialisée si nécessaire","produire un JSON structuré","conserver la session mémoire dans l’injection"],"pipeline":["édition ChatGPT","mémoire Aurore","validation JSON","ingestion Supabase","sas administratif","lancement PDF manuel","LuaLaTeX","contrôle PDF","publication humaine"],"hard_rules":["aucun moteur IA intermédiaire n’est requis pour le rendu PDF","le PDF et le contenu éditorial sont deux étapes distinctes","la publication reste humaine"],"memory_gate":"Une session mémoire valide, non expirée et non consommée est obligatoire avant l’insertion d’un document issu de l’ingestion éditoriale ChatGPT."}'::jsonb),
('document_structure',1,'Structure canonique d’un cours',950,
 '{"required_top_level":["title","sections"],"section_rules":["chaque section possède un titre non vide","le contenu est découpé en blocs pédagogiques courts","les formules importantes ne sont pas noyées dans de très longs paragraphes","les exercices et corrections restent séparables"],"recommended_sequence":["objectif","définition ou rappel","propriété ou méthode","formule","explication","exemple","application ou exercice","correction","synthèse"],"quality_gate":["pas de section vide","pas de répétition","éviter les blocs monolithiques lorsque plusieurs blocs sont possibles"]}'::jsonb),
('editorial_quality',1,'Qualité pédagogique et lisibilité',900,
 '{"rules":["progression pédagogique explicite","notations introduites avant usage intensif","idées essentielles faciles à repérer","exemples réellement liés à la notion","phrases et paragraphes lisibles"],"anti_patterns":["copier-coller d’une conclusion","annexe répétée","mélange explication et corrigé","contenu générique hors sujet"]}'::jsonb),
('exercise_and_correction',1,'Exercices et corrigés',850,
 '{"rules":["énoncé identifiable","correction rattachée à l’exercice","corrigé centré sur la question posée","calculs lisibles"],"profiles":{"cours":"les exercices complètent la leçon","exercices":"énoncés indépendants et corrections correspondantes"}}'::jsonb),
('visual_graph_policy',1,'Graphiques, constructions et visuels',800,
 '{"rules":["graphiques dans sections.graphs","illustrations documentaires dans sections.visuals","un graphique a un rôle pédagogique","un visuel documentaire apporte une information"],"limits":{"visuals_per_section":3,"visuals_per_document":8,"graphs_per_document":24},"supported_documentary_visual_type":"wikimedia"}'::jsonb),
('pdf_quality_qa',1,'Contrôle qualité du PDF',780,
 '{"preflight":["JSON valide","champs obligatoires présents","absence de duplication évidente","éléments mathématiques identifiables"],"pdf_checks":["texte normalement composé","pas de césure caractère par caractère","aucune section ou annexe répétée","mathématiques correctement composées","exercices et corrections distincts"],"lesson_from_document_364":"La validité JSON minimale ne suffit pas : la structure pédagogique conditionne la qualité du PDF."}'::jsonb),
('metadata_and_idempotence',1,'Traçabilité et idempotence',750,
 '{"required_metadata":["ingest_id","schema_version","content_sha256","human_review_required","manual_publication_only","memory_gate"],"rules":["ingest_id stable pendant les retries","versions de mémoire conservées","une réinjection ne crée pas de doublon"]}'::jsonb)
on conflict (rule_key,version) do update set title=excluded.title,priority=excluded.priority,mandatory=excluded.mandatory,active=true,content=excluded.content,updated_at=now();

insert into public.aurora_math_editorial_memory (rule_key,version,title,priority,content) values
('math_document_structure',1,'Structure d’un cours de mathématiques',1000,
 '{"rules":["séparer explication, propriété, exemple, formule, exercice et correction","éviter les blocs excessivement longs","utiliser une structure progressive","rendre les résultats importants repérables"],"recommended_sequence":["prérequis","définition","propriété","formule","justification","exemple","application","synthèse"]}'::jsonb),
('math_formula_blocks',1,'Formules et blocs mathématiques',990,
 '{"rules":["isoler les formules importantes lorsque le schéma le permet","garder les formules inline courtes","isoler les expressions longues, systèmes, matrices et calculs multilignes","ne pas transformer une formule longue en phrase"],"examples_valid":["probabilité conditionnelle","loi binomiale","fraction","racine","limite"],"avoid":["formule longue noyée dans le texte","même formule répétée sans raison"]}'::jsonb),
('math_latex_safe_syntax',1,'Syntaxe mathématique sûre pour LuaLaTeX',980,
 '{"principles":["utiliser des commandes LaTeX complètes","préférer une syntaxe proche du LaTeX valide","ne pas utiliser de commandes tronquées","ne pas imbriquer incorrectement les délimiteurs mathématiques"],"renderer_contract":"Le renderer normalise certaines erreurs mais le JSON doit rester proche d’un LaTeX correct."}'::jsonb),
('math_pedagogy',1,'Progression pédagogique des mathématiques',950,
 '{"rules":["définir les notations avant les applications","expliquer les paramètres avant la formule","justifier les transformations importantes","conserver conditions et domaines","terminer les grandes méthodes par une synthèse"],"course_example":"Pour une loi de probabilité : définition, paramètres, formule, interprétation, exemple, exercice."}'::jsonb),
('math_anti_patterns',1,'Pièges connus des productions Aurore',940,
 '{"forbidden":["répétition d’une application ou annexe","césure caractère par caractère","formule importante laissée uniquement en texte","copie d’un corrigé dans plusieurs exercices","leçon générique dans un PDF d’exercices","syntaxe mathématique volontairement approximative"],"case_reference":"Le document de probabilités 364 a nécessité une réécriture de structure avant d’obtenir un PDF nettement meilleur."}'::jsonb),
('math_pdf_qa',1,'Contrôle spécifique du PDF mathématique',930,
 '{"checklist":["fractions visuellement composées","puissances et indices correctement positionnés","symboles d’ensemble et limites lisibles","équations longues sans débordement","exercices et corrections distincts","aucune formule répétée sans raison","aucune annexe répétée"],"failure_action":"Corriger d’abord la structure du content_json avant de modifier le renderer."}'::jsonb),
('math_content_examples',1,'Patrons réutilisables pour les cours de mathématiques',900,
 '{"patterns":[{"name":"définition","shape":"texte court avec notation éventuelle"},{"name":"formule","shape":"énoncé, formule, interprétation"},{"name":"exemple","shape":"problème, calculs séparés, conclusion"},{"name":"méthode","shape":"étapes, conditions, résultat"},{"name":"exercice","shape":"énoncé indépendant, données explicites, correction associée"}],"rule":"Les patrons structurent le document mais ne doivent jamais être remplis par du contenu générique hors sujet."}'::jsonb)
on conflict (rule_key,version) do update set title=excluded.title,priority=excluded.priority,mandatory=excluded.mandatory,active=true,content=excluded.content,updated_at=now();

create or replace function public.aurora_enforce_editorial_memory_gate()
returns trigger
language plpgsql
security invoker
set search_path = public, pg_temp
as $function$
declare
  v_session public.aurora_editorial_memory_sessions;
  v_session_id uuid;
  v_subject text;
  v_requires_math boolean;
  v_general_count integer;
  v_math_count integer;
begin
  if coalesce(NEW.metadata->>'origin','') <> 'gpt_editorial_ingest' then
    return NEW;
  end if;
  if coalesce(trim(NEW.metadata->>'memory_session_id'),'') = '' then
    raise exception 'Mémoire éditoriale obligatoire : aucune session mémoire n’a été fournie';
  end if;
  begin
    v_session_id := (NEW.metadata->>'memory_session_id')::uuid;
  exception when others then
    raise exception 'Mémoire éditoriale invalide : memory_session_id doit être un UUID';
  end;
  v_subject := lower(trim(coalesce(nullif(NEW.matiere,''),nullif(NEW.subject,''),'')));
  v_requires_math := v_subject like '%math%';
  select * into v_session
  from public.aurora_editorial_memory_sessions
  where session_id=v_session_id and used_at is null and expires_at>now()
  for update;
  if not found then
    raise exception 'Mémoire éditoriale obligatoire : session absente, expirée ou déjà consommée';
  end if;
  v_general_count := coalesce(array_length(v_session.general_rule_ids,1),0);
  v_math_count := coalesce(array_length(v_session.math_rule_ids,1),0);
  if v_general_count<1 then
    raise exception 'Mémoire éditoriale obligatoire : le pack général n’a pas été récupéré';
  end if;
  if v_requires_math and (not v_session.requires_math or v_math_count<1) then
    raise exception 'Mémoire mathématique obligatoire : le pack Mathématiques n’a pas été récupéré';
  end if;
  if lower(trim(coalesce(v_session.requested_subject,'')))<>v_subject
     and not (v_requires_math and lower(trim(coalesce(v_session.requested_subject,''))) like '%math%') then
    raise exception 'Mémoire éditoriale incompatible avec la matière demandée';
  end if;
  NEW.metadata := coalesce(NEW.metadata,'{}'::jsonb) || jsonb_build_object(
    'memory_gate', jsonb_build_object(
      'verified', true,
      'session_id', v_session.session_id,
      'retrieved_at', v_session.retrieved_at,
      'expires_at', v_session.expires_at,
      'general_rule_ids', to_jsonb(v_session.general_rule_ids),
      'math_rule_ids', to_jsonb(v_session.math_rule_ids),
      'general_memory_version', v_session.general_memory_version,
      'math_memory_version', v_session.math_memory_version,
      'bundle_sha256', v_session.bundle_sha256
    )
  );
  return NEW;
end;
$function$;

create or replace function public.aurora_consume_editorial_memory_session()
returns trigger
language plpgsql
security invoker
set search_path = public, pg_temp
as $function$
declare
  v_session_id uuid;
begin
  if coalesce(NEW.metadata->>'origin','') <> 'gpt_editorial_ingest' then
    return NEW;
  end if;
  v_session_id := nullif(trim(NEW.metadata->>'memory_session_id'),'')::uuid;
  update public.aurora_editorial_memory_sessions
     set used_at=now(),
         used_ingest_id=NEW.ingest_id,
         metadata=coalesce(metadata,'{}'::jsonb) || jsonb_build_object('consumed_document_id',NEW.id,'consumed_at',now())
   where session_id=v_session_id and used_at is null;
  if not found then
    raise exception 'Mémoire éditoriale : session non consommable';
  end if;
  return NEW;
end;
$function$;

drop trigger if exists aurora_generated_documents_memory_gate on public.aurora_generated_documents;
create trigger aurora_generated_documents_memory_gate
before insert on public.aurora_generated_documents
for each row execute function public.aurora_enforce_editorial_memory_gate();

drop trigger if exists aurora_generated_documents_memory_consume on public.aurora_generated_documents;
create trigger aurora_generated_documents_memory_consume
after insert on public.aurora_generated_documents
for each row execute function public.aurora_consume_editorial_memory_session();

revoke all on function public.aurora_enforce_editorial_memory_gate() from public, anon, authenticated;
revoke all on function public.aurora_consume_editorial_memory_session() from public, anon, authenticated;
grant execute on function public.aurora_enforce_editorial_memory_gate() to service_role;
grant execute on function public.aurora_consume_editorial_memory_session() to service_role;