-- Aurore — protocole d’ingestion mémoire v3
-- Source: production Supabase ref tdeotqfsbvouresfhkab
-- Le protocole devient une dépendance obligatoire avant toute ingestion éditoriale ChatGPT.

create table if not exists public.aurora_editorial_family_memory (
  id bigint generated by default as identity primary key,
  family_key text not null,
  version integer not null default 1 check (version > 0),
  title text not null,
  priority integer not null default 100,
  mandatory boolean not null default true,
  active boolean not null default true,
  content jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (family_key,version)
);

create unique index if not exists aurora_editorial_family_memory_active_uq
  on public.aurora_editorial_family_memory (family_key) where active;

alter table public.aurora_editorial_family_memory enable row level security;
revoke all on public.aurora_editorial_family_memory from public,anon,authenticated;
grant select on public.aurora_editorial_family_memory to service_role;

insert into public.aurora_editorial_memory
(rule_key,version,title,priority,mandatory,active,content)
values
('document_insertion_protocol',1,'Protocole canonique d’insertion Aurore — obligatoire avant toute génération',2000,true,true,
'{
 "purpose":"Manuel opératoire central pour toute IA qui génère puis injecte un document dans Aurore — Section Archives.",
 "non_negotiable":["Lire ce protocole avant la génération finale.","Obtenir une session mémoire officielle avant la génération finale destinée à l’injection.","Accuser réception de toutes les couches du paquet mémoire.","Utiliser uniquement le contrat d’injection prévu.","Ne jamais contourner la barrière mémoire PostgreSQL.","Ne pas créer ou déposer directement un PDF de production depuis l’étape éditoriale.","Ne jamais publier automatiquement."],
 "canonical_flow":["déterminer matière, niveau, classe et type réel","récupérer la mémoire","lire protocole + structure + famille + matière/sous-profil + type documentaire","accuser réception","générer content_json","valider la structure","appeler aurora-gpt-ingest","laisser Supabase consommer la session","contrôle humain","lancement manuel aurora-lualatex-request","GitHub Actions/LuaLaTeX/GeoGebra/QA","retour Content Factory","validation puis publication humaine"],
 "targets":{"request":"aurora_content_jobs = sas/demande","editorial_document":"aurora_generated_documents = contenu structuré + content_json","pdf":"produit après lancement du pipeline LuaLaTeX","storage":"alimenté par le pipeline PDF et non par l’IA éditoriale"},
 "before_injection":["matière/niveau/type cohérents","title et introduction corrects pour un cours","sections structurées","formules correctement placées","exercices et corrections séparés","graphiques/visuels justifiés","pour les maths, décision graphique explicite pour les notions graphables","3 000 mots utiles pour un cours standard","absence de duplication"],
 "failure_policy":"Corriger le content_json avant de modifier le renderer."
}'::jsonb),
('document_type_profiles',1,'Profils documentaires transversaux Aurore',1990,true,true,
'{"course-v2":{"required":["title","introduction","sections"],"minimum_useful_words":3000,"short_format_requires_reason":true},"exercise-sheet-v2":{"exercise_location":"sections[].exercises[]","correction_location":"corrections","pairing_required":true,"forbidden":["correction inline","exercise hidden in content","generic lesson","duplication"]},"document-v1":{"rule":"adapter la structure à la finalité réelle sans inventer une structure disciplinaire"}}'::jsonb),
('pdf_production_protocol',1,'Séparation ingestion éditoriale et production PDF',1980,true,true,
'{"editorial_stage":"IA -> mémoire -> JSON -> aurora-gpt-ingest -> review/sas","pdf_stage":"admin -> aurora-lualatex-request -> GitHub Actions -> GeoGebra/QA -> LuaLaTeX -> upload -> Content Factory","never":["auto-dispatch PDF depuis ingestion","uploader directement le PDF final depuis l’IA","auto-publier","modifier le renderer pour corriger une mauvaise structure éditoriale"]}'::jsonb),
('known_production_failures',1,'Mémoire de prévention — erreurs historiques Aurore',1970,true,true,
'{"exercise_365":{"failure":"exercices cachés dans section.content","prevention":"sections[].exercises[] + corrections[] + appariement"},"geogebra_370":{"failure":"cours sans introduction et content mal typé","prevention":"introduction explicite + content structuré"},"pdf_364":{"failure":"JSON valide mais PDF pédagogiquement insuffisant","prevention":"QA du rendu réel"},"latex":{"failure":"commandes LaTeX mal formées","prevention":"syntaxe structurée et aucun moteur intermédiaire pour réécrire arbitrairement les formules"},"graph":{"failure":"graphique déclaré sans données exploitables","prevention":"graph_id stable + instrument supporté + source + bornes valides + asset récupérable"},"volume":{"failure":"cours trop court ou gonflé artificiellement","prevention":"3 000 mots utiles ou format court justifié"}}'::jsonb),
('cross_discipline_routing',1,'Routage disciplinaire pour toutes les matières',1960,true,true,
'{"inheritance_order":["protocole général","structure/routage","famille","matière","sous-profil","profil documentaire","validators"],"families":["mathematics","physical_sciences","life_earth_sciences","languages","humanities","social_sciences","computer_science","arts_sports","generic"],"unknown_subject":"Utiliser generic et signaler la spécialisation manquante; ne jamais inventer silencieusement une règle de matière."}'::jsonb)
on conflict (rule_key,version) do update set title=excluded.title,priority=excluded.priority,mandatory=excluded.mandatory,active=true,content=excluded.content,updated_at=now();

insert into public.aurora_editorial_family_memory
(family_key,version,title,priority,mandatory,active,content)
values
('mathematics',1,'Famille Mathématiques',1000,true,true,'{"principles":["raisonnement symbolique","formules structurées","domaines et conditions","représentation graphique pertinente","GeoGebra lorsque supporté"]}'::jsonb),
('physical_sciences',1,'Famille Physique-Chimie',1000,true,true,'{"principles":["lois et relations scientifiques","grandeurs et unités","calculs","interprétation physique","schémas et graphes utiles"]}'::jsonb),
('life_earth_sciences',1,'Famille SVT',1000,true,true,'{"principles":["notions et mécanismes","observation/interprétation/conclusion","schémas et documents utiles"]}'::jsonb),
('languages',1,'Famille Langues',1000,true,true,'{"principles":["niveau linguistique","lexique","grammaire","activités et corrections séparées"]}'::jsonb),
('humanities',1,'Famille Humanités',1000,true,true,'{"principles":["notions","documents identifiés","analyse","argumentation","distinction faits/interprétations"]}'::jsonb),
('social_sciences',1,'Famille Sciences humaines et sociales',1000,true,true,'{"principles":["concepts","données","sources","interprétation","méthodes explicites"]}'::jsonb),
('computer_science',1,'Famille Informatique',1000,true,true,'{"principles":["algorithmes","code structuré","étapes reproductibles","tests"]}'::jsonb),
('arts_sports',1,'Famille Arts et EPS',1000,true,true,'{"principles":["objectifs","compétences","consignes","supports utiles","évaluation distincte"]}'::jsonb),
('generic',1,'Famille générique de repli',1,true,true,'{"principles":["protocole général","aucune contrainte disciplinaire inventée","spécialisation manquante à signaler"]}'::jsonb)
on conflict (family_key,version) do update set title=excluded.title,priority=excluded.priority,mandatory=excluded.mandatory,active=true,content=excluded.content;

update public.aurora_math_editorial_memory
set content=content || jsonb_build_object(
 'mandatory_ingestion_gate',true,
 'general_ingestion_notes',jsonb_build_array(
  'La mémoire générale et Mathématiques doivent être récupérées dans la même session avant la génération finale.',
  'Pour chaque section graphable, décider build ou not_needed.',
  'Une décision build exige des graph_ids réels dans la section.',
  'Un graphique annoncé mais non construit ou non inséré bloque la validation PDF.'
 )
where rule_key in ('math_graphical_representation','geogebra_construction_quality');

create or replace function public.aurora_enforce_editorial_memory_gate()
returns trigger
language plpgsql
security invoker
set search_path=public,pg_temp
as $function$
declare
  v_session public.aurora_editorial_memory_sessions;
  v_session_id uuid;
  v_subject text;
  v_requires_math boolean;
  v_gate jsonb;
  v_expected jsonb;
  v_general_count integer;
  v_math_count integer;
  v_structure_count integer;
begin
  if coalesce(NEW.metadata->>'origin','') <> 'gpt_editorial_ingest' then return NEW; end if;
  if coalesce(NEW.metadata->>'memory_schema','') <> 'aurora-editorial-memory-3' then
    raise exception 'Memoire editoriale obligatoire : version de paquet memoire invalide';
  end if;
  v_gate:=coalesce(NEW.metadata->'editorial_memory_gate','{}'::jsonb);
  if coalesce(v_gate->>'read_confirmed','false')<>'true' or coalesce(v_gate->>'verified','false')<>'true' then
    raise exception 'Lecture obligatoire : les consignes editoriales doivent etre lues et attestees avant injection';
  end if;
  begin v_session_id:=nullif(trim(NEW.metadata->>'memory_session_id'),'')::uuid;
  exception when others then raise exception 'Memoire editoriale invalide : memory_session_id doit etre un UUID'; end;
  select * into v_session from public.aurora_editorial_memory_sessions
   where session_id=v_session_id and used_at is null and expires_at>now() for update;
  if not found then raise exception 'Memoire editoriale obligatoire : session absente, expiree ou deja consommee'; end if;
  if coalesce(v_session.metadata->>'memory_schema','')<>'aurora-editorial-memory-3' then
    raise exception 'Memoire editoriale obligatoire : session issue d’une ancienne version';
  end if;
  if nullif(trim(v_gate->>'session_id'),'') is distinct from v_session_id::text then raise exception 'Lecture obligatoire : session_id invalide'; end if;
  if nullif(trim(v_gate->>'bundle_sha256'),'') is distinct from v_session.bundle_sha256 then raise exception 'Lecture obligatoire : paquet memoire different'; end if;

  v_expected:=jsonb_build_object(
    'session_id',v_session.session_id::text,'bundle_sha256',v_session.bundle_sha256,
    'protocol_version',v_session.metadata #>> '{editorial_read_gate,protocol_version}',
    'protocol_sha256',v_session.metadata #>> '{editorial_read_gate,protocol_sha256}',
    'general_rule_keys',coalesce(v_session.metadata #> '{editorial_read_gate,general_rule_keys}','[]'::jsonb),
    'structure_rule_keys',coalesce(v_session.metadata #> '{editorial_read_gate,structure_rule_keys}','[]'::jsonb),
    'math_rule_keys',coalesce(v_session.metadata #> '{editorial_read_gate,math_rule_keys}','[]'::jsonb),
    'family_key',v_session.metadata #>> '{editorial_read_gate,family_key}',
    'family_version',nullif(v_session.metadata #>> '{editorial_read_gate,family_version}','')::int,
    'family_sha256',v_session.metadata #>> '{editorial_read_gate,family_sha256}',
    'subject_profile_key',v_session.metadata #>> '{editorial_read_gate,subject_profile_key}',
    'subject_profile_version',nullif(v_session.metadata #>> '{editorial_read_gate,subject_profile_version}','')::int,
    'subject_profile_sha256',v_session.metadata #>> '{editorial_read_gate,subject_profile_sha256}',
    'document_profile_key',v_session.metadata #>> '{editorial_read_gate,document_profile_key}',
    'document_profile_version',nullif(v_session.metadata #>> '{editorial_read_gate,document_profile_version}','')::int,
    'document_profile_sha256',v_session.metadata #>> '{editorial_read_gate,document_profile_sha256}'
  );

  if coalesce(v_gate->>'protocol_version','')<>coalesce(v_expected->>'protocol_version','')
  or coalesce(v_gate->>'protocol_sha256','')<>coalesce(v_expected->>'protocol_sha256','')
  or coalesce(v_gate->>'family_key','')<>coalesce(v_expected->>'family_key','')
  or coalesce(v_gate->>'family_version','')<>coalesce(v_expected->>'family_version','')
  or coalesce(v_gate->>'family_sha256','')<>coalesce(v_expected->>'family_sha256','')
  or coalesce(v_gate->>'document_profile_key','')<>coalesce(v_expected->>'document_profile_key','')
  or coalesce(v_gate->>'document_profile_version','')<>coalesce(v_expected->>'document_profile_version','')
  or coalesce(v_gate->>'document_profile_sha256','')<>coalesce(v_expected->>'document_profile_sha256','')
  or coalesce(v_gate->>'subject_profile_key','')<>coalesce(v_expected->>'subject_profile_key','')
  or coalesce(v_gate->>'subject_profile_version','')<>coalesce(v_expected->>'subject_profile_version','')
  or coalesce(v_gate->>'subject_profile_sha256','')<>coalesce(v_expected->>'subject_profile_sha256','') then
    raise exception 'Lecture obligatoire : une couche memoire de routage/profil ne correspond pas a la session';
  end if;

  if coalesce(v_gate->'general_rule_keys','[]'::jsonb)<>coalesce(v_expected->'general_rule_keys','[]'::jsonb)
  or coalesce(v_gate->'structure_rule_keys','[]'::jsonb)<>coalesce(v_expected->'structure_rule_keys','[]'::jsonb)
  or coalesce(v_gate->'math_rule_keys','[]'::jsonb)<>coalesce(v_expected->'math_rule_keys','[]'::jsonb) then
    raise exception 'Lecture obligatoire : liste des regles lues incomplete ou differente';
  end if;

  if nullif(trim(v_gate->>'ack_sha256'),'') is null
     or nullif(trim(v_gate->>'ack_sha256'),'') is distinct from (v_session.metadata #>> '{editorial_read_gate,ack_sha256}') then
    raise exception 'Lecture obligatoire : attestation cryptographique invalide';
  end if;

  v_subject:=lower(trim(coalesce(nullif(NEW.matiere,''),nullif(NEW.subject,''),'')));
  v_requires_math:=v_subject like '%math%';
  v_general_count:=coalesce(array_length(v_session.general_rule_ids,1),0);
  v_math_count:=coalesce(array_length(v_session.math_rule_ids,1),0);
  v_structure_count:=jsonb_array_length(coalesce(v_session.metadata #> '{editorial_read_gate,structure_rule_keys}','[]'::jsonb));
  if v_general_count<1 then raise exception 'Memoire editoriale obligatoire : pack general absent'; end if;
  if v_structure_count<1 then raise exception 'Memoire editoriale obligatoire : pack structure absent'; end if;
  if v_requires_math and (not v_session.requires_math or v_math_count<1) then raise exception 'Memoire mathematique obligatoire : pack absent'; end if;

  NEW.metadata:=coalesce(NEW.metadata,'{}'::jsonb)||jsonb_build_object('memory_gate',
    jsonb_build_object(
      'verified',true,'read_confirmed',true,'memory_schema','aurora-editorial-memory-3',
      'session_id',v_session.session_id,'retrieved_at',v_session.retrieved_at,'expires_at',v_session.expires_at,
      'general_rule_ids',to_jsonb(v_session.general_rule_ids),'math_rule_ids',to_jsonb(v_session.math_rule_ids),
      'general_memory_version',v_session.general_memory_version,'math_memory_version',v_session.math_memory_version,
      'bundle_sha256',v_session.bundle_sha256,'protocol_version',v_expected->>'protocol_version','protocol_sha256',v_expected->>'protocol_sha256',
      'general_rule_keys',v_expected->'general_rule_keys','structure_rule_keys',v_expected->'structure_rule_keys','math_rule_keys',v_expected->'math_rule_keys',
      'family_key',v_expected->>'family_key','family_version',v_expected->>'family_version','family_sha256',v_expected->>'family_sha256',
      'subject_profile_key',v_expected->>'subject_profile_key','subject_profile_version',v_expected->>'subject_profile_version','subject_profile_sha256',v_expected->>'subject_profile_sha256',
      'document_profile_key',v_expected->>'document_profile_key','document_profile_version',v_expected->>'document_profile_version','document_profile_sha256',v_expected->>'document_profile_sha256',
      'ack_sha256',v_session.metadata #>> '{editorial_read_gate,ack_sha256}'
    ));
  return NEW;
end;
$function$;
